  
CREATE SEQUENCE SEQ_PRODUCTO;

CREATE SEQUENCE SEQ_USUARIO
MINVALUE 1 
INCREMENT BY 1 
START WITH 1;

CREATE SEQUENCE SEQ_HISTORICO_PRECIO;

CREATE SEQUENCE SEQ_CLIENTE;

CREATE SEQUENCE SEQ_PROVEEDOR;

CREATE SEQUENCE SEQ_EMPLEADO;